theme = "github_dark"

[editor]
mouse = false
bufferline = "multiple"

[editor.inline-diagnostics]
cursor-line = "error"
other-lines = "error"
 
[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"

[keys.normal]
C-s = ":write"
C-n = "page_cursor_half_up"
C-t = "page_cursor_half_down"
C-x = ":buffer-close"

esc = ["collapse_selection", "keep_primary_selection"]

h = "move_char_left"
t = "move_visual_line_down"
n = "move_visual_line_up"
s = "move_char_right"

o = "move_prev_word_start"
e = "move_next_word_end"
w = "no_op"

[keys.normal.g]
h = "goto_line_start"
t = "goto_previous_buffer"
n = "goto_next_buffer"
s = "goto_line_end"

[keys.normal.a]
h = "jump_view_left"
t = "jump_view_down"
n = "jump_view_up"
s = "jump_view_right"
x = "wclose"
v = "vsplit"
w = "hsplit"
