theme = "jetbrains_dark"                                                                                                                                                               

[editor]
mouse = false
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"

[keys.normal]
C-s = ":write"
C-n = "page_cursor_half_up"
C-t = "page_cursor_half_down"
C-x = ":buffer-close"

esc = ["collapse_selection", "keep_primary_selection"]

h = "move_char_left"
t = "move_visual_line_down"
n = "move_visual_line_up"
s = "move_char_right"

m = "move_prev_word_start"

[keys.normal.g]
n = "goto_next_buffer"
t = "goto_previous_buffer"
h = "goto_line_start"
s = "goto_line_end"
